### ISSUE TITLE
[ISSUE]: Only 1 trusted_domain is being added, in nextcloudpi even after adding 3 domains

### ISSUE THREAD

**Issue by shubham947** [novaspirit/pi-hosted#128] opened 2021-11-05 19:37 UTC
**Issue**
Only 1 `trusted_domain` is being added, in **nextcloudpi** even after adding 3 domains.

**Example**
If I add these:
```
Trusted Domain #1: cloud.example.com
Trusted Domain #2: 172.35.0.2
Trusted Domain #3: 192.168.0.2
```
Then only last address is being added to `trusted_domains`,
```
trusted_domains: {
    ...
    22=> 192.168.0.2
    ...
}
```

**Comment by rmiddle** [comment] 2021-11-06 01:02
This needs to be added to the NextCloudPi issue queue as it isn't a problem with the template but instead NextCloudPi software

**Comment by rmiddle** [comment] 2021-11-06 01:04
Submitted NextCloudPI

https://github.com/nextcloud/nextcloudpi/issues/1379

**Comment by rmiddle** [comment] 2021-11-06 21:21
Issue is fixed in tree waiting for the docker provider to push the latest release out that includes the fix.

**Comment by rmiddle** [comment] 2021-11-11 23:14
The problem is in the docker image and should be fixed in the next release.  Closing.

**Closed by rmiddle** 2021-11-11 23:14 UTC
Labels: bug
